default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: <%= ENV[DBNAMEDEV] %>
  host: <%= ENV[DBHOST] %>
  username: <%= ENV[DBUSERNAME] %>
  password: <%= ENV[DBPASSWORD] %>

test:
  <<: *default
  database: <%= ENV[DBNAMETEST] %>
  host: <%= ENV[DBHOST] %>
  username: <%= ENV[DBUSERNAME] %>
  password: <%= ENV[DBPASSWORD] %>


# Do not keep production credentials in the repository,
# instead read the configuration from the environment.
#
# Example:
#   postgresql://myuser:mypass@localhost/full/path/to/somedatabase
#
production:
  <<: *default
  database: <%= ENV[DBNAMEPROD] %>
  host: <%= ENV[DBHOST] %>
  username: <%= ENV[DBUSERNAME] %>
  password: <%= ENV[DBPASSWORD] %>
  # url: <%= ENV["DATABASE_URL"] %>
