# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb6934ec127bc460a32b77ffa778d4840b325b4bc7e7f0415e6f246136e9528fa420aa92d19fdbf8cb7ec3779cb647443c241da451021a28471aee07b2a4f5d0

test:
  secret_key_base: 19eca8c413f3baf9a4029c7e603a184121e3bfa507d418b7b4d616881d4301ed578aa19d7ad88b002860d68e75b375bea6664c16a3d7d0d51545a279fafbef1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
